title = "JASMIN Help Site"
copyright = "Copyright © 2025 Science and Technology Facilities Council."
enableGitInfo = false #true #for production

# additional settings
baseURL = 'https://help.jasmin.ac.uk' # temp value until we have a domain
canonifyURLs = false
enableEmoji = true
enableRobotsTXT = true
enableInlineShortcodes = true
summaryLength = 20
Parser.wrapStandAloneImageWithinParagraph = false # see https://gethinode.com/docs/content/images-and-figures/

# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreLogs = ["error-remote-getjson"] # , "warn-invalid-arguments"

timeout = "600s"

languageCode = "en-gb"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[build]
  writeStats = true

[taxonomies]
  tag = 'tags'

[pagination]
  pagerSize = 12

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.x]
    disableInlineCSS = true
  [services.googleAnalytics]
    ID = "G-JJZZ5F2KN4"

[outputFormats]
  [outputFormats.server]
    mediaType = "application/toml"
    baseName = "server"
    isPlainText = true
    notAlternative = true
    permalinkable = true
    root = true
  [outputFormats.netlify]
    mediaType = "application/toml"
    baseName = "netlify"
    isPlainText = true
    notAlternative = true
    permalinkable = true
    root = true
  [outputFormats.XML]
    isPlainText = false
    mediaType = "application/xml"
    isHtml = false
    noUgly = true
    permalinkable = false
    name = "xml"
  #[outputFormats.REDIR]
  #  mediaType = "text/netlify"
  #  baseName = "_redirects"
  #  isPlainText = true
  #  notAlternative = true

[outputs]
home = ["HTML", "RSS", "REDIR", "netlify", "server"]

[minify] # see https://discourse.gohugo.io/t/minify-config-tutorials/28179/5
  disableHTML = false
  disableJS = true
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = true
    [minify.tdewolff.js]
      keepVarNames = true
      precision = 0
      keepWhitespace = true

[segments]
  [segments.headers]
    [[segments.headers.includes]]
       kind = '{home}'
       output = '{netlify,server}'

[module]
  #[[module.imports]]
  #  path = "github.com/gethinode/mod-cookieyes/v2"
  [[module.imports]]
    path = "github.com/gethinode/hinode"