#[[main]]
#  name = "Blocks"
#  pageRef = "/blocks/"
#  weight = 10

[[main]]
  name = "Docs"
  pageRef = "/docs/"
  weight = 10

[[main]]
  name = "Discussions"
  url = "https://github.com/cedadev/jasmin-community/discussions"
  weight = 60

[[social]]
  name = "YouTube"
  pre = "fab fa-youtube"
  url = "https://www.youtube.com/channel/UCYjSH2ET9nLMhDcXa5y2OMg"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/cedadev"
  weight = 2
